# Generated by Django 5.0.1 on 2024-06-25 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
