# Generated by Django 5.0.1 on 2024-06-27 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_remove_author_bio_ar_remove_author_bio_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
