# Generated by Django 5.0.1 on 2024-06-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_author_options_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mything',
            name='name',
            field=models.CharField(help_text='This is the help text', max_length=200),
        ),
    ]
