# Generated by Django 5.0.1 on 2024-06-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_mything_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_ar', models.CharField(help_text='MyModel name in Arabic', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='MyThing',
        ),
    ]
