# Generated by Django 5.0.1 on 2024-06-28 14:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
        ('sessions', '0001_initial'),
        ('store', '0019_mymodel_delete_mything'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio_ar',
            field=models.TextField(null=True, unique=True, verbose_name='سيرة ذاتية'),
        ),
        migrations.AddField(
            model_name='author',
            name='name_ar',
            field=models.CharField(default='اسم افتراضي', max_length=255, verbose_name='الاسم بالعربية'),
        ),

        migrations.AddField(
            model_name='category',
            name='name_ar',
            field=models.CharField(default='اسم افتراضي', max_length=255, verbose_name='اسم'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_ar',
            field=models.TextField(default='وصف افتراضي', verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_ar',
            field=models.CharField(default='عنوان افتراضي', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AddField(
            model_name='product',
            name='description_ar',
            field=models.TextField(default='وصف افتراضي', null=True, verbose_name='وصف'),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ar',
            field=models.CharField(default='اسم افتراضي', max_length=255, verbose_name='اسم'),
        ),
        migrations.AddField(
            model_name='product',
            name='short_description_ar',
            field=models.TextField(default='وصف قصير افتراضي', null=True, verbose_name='وصف قصير'),
        ),
        migrations.AddField(
            model_name='slider',
            name='subtitle_ar',
            field=models.TextField(default='العنوان الفرعي الافتراضي', max_length=500, verbose_name='العنوان الفرعي'),
        ),
        migrations.AddField(
            model_name='slider',
            name='title_ar',
            field=models.CharField(default='عنوان افتراضي', max_length=255, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(null=True, verbose_name='Bio'),
        ),
        migrations.AlterField(
            model_name='author',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.JSONField(default=dict, verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sessions.session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='category',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='category',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='name_ar',
            field=models.CharField(help_text='MyModel name in Arabic', max_length=255, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='checkout.transaction', verbose_name='Transaction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.order', verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='product',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.author', verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Featured'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(null=True, upload_to='', verbose_name='PDF File'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='product_videos/', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subtitle',
            field=models.TextField(max_length=500, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
