# Generated by Django 5.0.1 on 2024-06-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_category_name_ar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='bio_ar',
            field=models.TextField(null=True, verbose_name='سيرة ذاتية'),
        ),
    ]
